/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_l1yp_SilkCodec */

#ifndef _Included_com_l1yp_SilkCodec
#define _Included_com_l1yp_SilkCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_l1yp_SilkCodec
 * Method:    processStreams
 * Signature: ([BLjava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_l1yp_SilkCodec_processStreams
  (JNIEnv *, jobject, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
